[package]
org = "ballerinax"
name = "health.fhir.templates.international401.medicinalproductinteraction"
version = "2.0.0"
distribution = "2201.7.0"
authors = ["Ballerina", "Healthcare", "FHIR"]
keywords = ["MedicinalProductInteraction", "r4", "health.fhir.templates.international401"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"
template = true

